spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/favorites
  thymeleaf:
    cache: false
    suffix: .html
    prefix: classpath:/templates/
  devtools:
    restart:
      enabled: true

