spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/favorites
  devtools:
    restart:
      enabled: true
